FROM nvidia/cuda:8.0-cudnn6-runtime-ubuntu16.04

MAINTAINER Ravi Kiran Kummamuru <ravikiran.kummamuru@zemosolabs.com>

ARG ANACONDA_VERSION=5.0.0.1
ARG TENSORFLOW_VERSION=1.3.0
ARG TENSORFLOW_ARCH=gpu
ARG KERAS_VERSION=2.0.8

ENV ANACONDA_DIR /opt/anaconda
ENV PATH $ANACONDA_DIR/bin:$PATH
ENV GIT_LFS_VER=2.1.1


# Download anaconda and install it
RUN apt-get update && apt-get install -y wget build-essential libssl-dev 
RUN apt-get install -y lsb-release
RUN wget http://repo.continuum.io/archive/Anaconda2-${ANACONDA_VERSION}-Linux-x86_64.sh -P /tmp
RUN bash /tmp/Anaconda2-${ANACONDA_VERSION}-Linux-x86_64.sh -b -p $ANACONDA_DIR
RUN rm /tmp/Anaconda2-${ANACONDA_VERSION}-Linux-x86_64.sh
RUN conda install git


# Install TensorFlow
RUN pip --no-cache-dir install	https://storage.googleapis.com/tensorflow/linux/${TENSORFLOW_ARCH}/tensorflow_${TENSORFLOW_ARCH}-${TENSORFLOW_VERSION}-cp27-none-linux_x86_64.whl

WORKDIR /tmp

## Install git-lfs
RUN curl -L https://github.com/git-lfs/git-lfs/releases/download/v$GIT_LFS_VER/git-lfs-linux-amd64-$GIT_LFS_VER.tar.gz \
   | tar xvzf - \
   && git-lfs-$GIT_LFS_VER/install.sh \
   && rm -rf git-lfs-$GIT_LFS_VER

## Install all the python packages
RUN pip install --upgrade pip \
   && pip install --upgrade \
      setuptools \
   && pip install --upgrade \
#      tensorflow==1.3.0 \
#	https://index.taskcluster.net/v1/task/project.deepspeech.tensorflow.pip.master.gpu/artifacts/public/tensorflow_gpu_warpctc-1.3.0rc0-cp27-cp27mu-linux_x86_64.whl \
      pyxdg \
      python_speech_features \
      sox \
      pandas

# Install keras
RUN pip install keras==${KERAS_VERSION}

# Install cloud tools: AWS
RUN pip install awscli

WORKDIR /docsaws/projects/
RUN git clone https://github.com/mozilla/DeepSpeech \
   && cd DeepSpeech \
   && pip install pandas \
	progressbar2 \
	python-utils \
#	tensorflow \
	numpy \
	matplotlib \
	scipy \
	paramiko \
	pysftp \
	sox \
	python_speech_features \
	pyxdg \
	bs4 \
	six 

RUN wget https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.cpu/artifacts/public/native_client.tar.xz -P /tmp \
        && cd /tmp \
        && tar -xJvf native_client.tar.xz \
        && cp -r *.so /docsaws/projects/DeepSpeech/native_client/

WORKDIR DeepSpeech
